title: Saffat Rahman Khan
logo: ![Image](https://github.com/user-attachments/assets/6957f5a7-efc5-48b4-ad9d-1448de3615dc)
#description: text below image
show_downloads: true
theme: jekyll-theme-minimal
